name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore CarDealership/CarDealership.csproj  # Update this path

    - name: Build the project
      run: dotnet build CarDealership/CarDealership.csproj --configuration Release --no-restore  # Update this path

    - name: Publish the project
      run: dotnet publish CarDealership/CarDealership.csproj --configuration Release --output ./artifacts  # Update this path
