public class StudentRepository
{
    private string connectionString = @"Data Source=DESKTOP-HEEKBHE\SQLEXPRESS;Initial Catalog=schooldb;Integrated Security=True";

    public void AddStudent(Student student)
    {
        using (SqlConnection con = new SqlConnection(connectionString))
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("INSERT INTO studentab VALUES (@StudentId, @StudentName, @Dob, @Gender, @Phone, @Email)", con);
            cmd.Parameters.AddWithValue("@StudentId", student.StudentId);
            cmd.Parameters.AddWithValue("@StudentName", student.StudentName);
            cmd.Parameters.AddWithValue("@Dob", student.Dob);
            cmd.Parameters.AddWithValue("@Gender", student.Gender);
            cmd.Parameters.AddWithValue("@Phone", student.Phone);
            cmd.Parameters.AddWithValue("@Email", student.Email);
            cmd.ExecuteNonQuery();
        }
    }

    // Other methods (UpdateStudent, DeleteStudent, GetAllStudents, etc.)
}

public class StudentService
{
    private StudentRepository _studentRepository = new StudentRepository();

    public void SaveStudent(Student student)
    {
        // Add any validation or business rules here
        _studentRepository.AddStudent(student);
    }

    // Other methods (UpdateStudent, DeleteStudent, etc.)
}


private void btnSave_Click(object sender, EventArgs e)
{
    var student = new Student
    {
        StudentId = int.Parse(textBox1.Text),
        StudentName = textBox2.Text,
        Dob = dateTimePicker1.Value,
        Gender = textBox3.Text,
        Phone = textBox4.Text,
        Email = textBox5.Text
    };

    var studentService = new StudentService();
    studentService.SaveStudent(student);
    MessageBox.Show("Record Saved Successfully", "Save", MessageBoxButtons.OK, MessageBoxIcon.Information);
}


